// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: core/proto/msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *MsgBase) Reset() {
	*x = MsgBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBase) ProtoMessage() {}

func (x *MsgBase) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBase.ProtoReflect.Descriptor instead.
func (*MsgBase) Descriptor() ([]byte, []int) {
	return file_core_proto_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MsgBase) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MyFirstReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hello []byte `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
}

func (x *MyFirstReq) Reset() {
	*x = MyFirstReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyFirstReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyFirstReq) ProtoMessage() {}

func (x *MyFirstReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyFirstReq.ProtoReflect.Descriptor instead.
func (*MyFirstReq) Descriptor() ([]byte, []int) {
	return file_core_proto_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MyFirstReq) GetHello() []byte {
	if x != nil {
		return x.Hello
	}
	return nil
}

type MyFirstAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word []byte `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *MyFirstAck) Reset() {
	*x = MyFirstAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyFirstAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyFirstAck) ProtoMessage() {}

func (x *MyFirstAck) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyFirstAck.ProtoReflect.Descriptor instead.
func (*MyFirstAck) Descriptor() ([]byte, []int) {
	return file_core_proto_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MyFirstAck) GetWord() []byte {
	if x != nil {
		return x.Word
	}
	return nil
}

var File_core_proto_msg_proto protoreflect.FileDescriptor

var file_core_proto_msg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x07, 0x4d,
	0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x22, 0x0a, 0x0a, 0x4d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x20, 0x0a, 0x0a, 0x4d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41,
	0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x73, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_proto_msg_proto_rawDescOnce sync.Once
	file_core_proto_msg_proto_rawDescData = file_core_proto_msg_proto_rawDesc
)

func file_core_proto_msg_proto_rawDescGZIP() []byte {
	file_core_proto_msg_proto_rawDescOnce.Do(func() {
		file_core_proto_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_proto_msg_proto_rawDescData)
	})
	return file_core_proto_msg_proto_rawDescData
}

var file_core_proto_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_proto_msg_proto_goTypes = []interface{}{
	(*MsgBase)(nil),    // 0: msg.MsgBase
	(*MyFirstReq)(nil), // 1: msg.MyFirstReq
	(*MyFirstAck)(nil), // 2: msg.MyFirstAck
}
var file_core_proto_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_proto_msg_proto_init() }
func file_core_proto_msg_proto_init() {
	if File_core_proto_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_proto_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyFirstReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyFirstAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_proto_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_msg_proto_goTypes,
		DependencyIndexes: file_core_proto_msg_proto_depIdxs,
		MessageInfos:      file_core_proto_msg_proto_msgTypes,
	}.Build()
	File_core_proto_msg_proto = out.File
	file_core_proto_msg_proto_rawDesc = nil
	file_core_proto_msg_proto_goTypes = nil
	file_core_proto_msg_proto_depIdxs = nil
}
